### ISSUE TITLE
Read receipts stopped working

### ISSUE THREAD

**Issue by Morse6690** [olvid-io/olvid-android#18]
After the latest update to 0.14.1 my receive receipts and read receipts all stopped working.
I get the single tick to show a message was sent. But no second tick, and no turning blue.

**Comment by finiasz** [comment]
Hello @Morse6690, contrary to messages which are also received through the REST api, return receipt can only be received through the WebSocket connection to our server. This kind of behavior looks like an issue with the WebSocket. Could you try enabling the "Network Connectivity Indicator" in "Other Settings":
![Screenshot_1684308885](https://github.com/olvid-io/olvid-android/assets/62558312/6e7be89c-ceda-4016-adce-22709458cd03)

This indicator is also based on the WebSocket. If it turns green, the problem is somewhere else... If it stays red, we need to understand why your WebSocket can't connect! Do you have any VPN/Proxy enabled on the phone?

**Comment by Morse6690** [comment]
That's a neat way to implement it with the dot. Yep shows up as green and now those conversations have all shown their read receipts.
Could be the VPN is interfering with things. I'll keep an eye on this.
Thanks again.

**Comment by finiasz** [comment]
Sure, don't hesitate to reopen the issue if needed. Also, sometimes the websocket may lose the connection and fail to reconnect. Force quitting the app and re-opening it can solve the problem.
